// Types
import { ReactNode } from "react";

// Components
import Navbar from "../navbar/Navbar";

// Native components
import Head from "next/head";

// Hooks
import { useState, useEffect } from "react";

interface Props {
  children: ReactNode;
}

export default function Layout({ children }: Props) {
  // Setting state to theme
  const [theme, setTheme] = useState("light");

  // Add/Remove dark class whenever the theme is changed
  useEffect(() => {
    if (theme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  }, [theme]);

  // Switches theme based on current state and click
  const handleThemeSwitch = () => {
    setTheme(theme === "dark" ? "light" : "dark");
  };
  return (
    <>
      <Head>
        <title>REST COUNTRIES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar theme={theme} changeTheme={handleThemeSwitch}></Navbar>
      <main className="min-h-screen min-w-screen darkMode dark:bg-dark-mode-background dark:text-dark-mode-text transition-all duration-300">{children}</main>
    </>
  );
}
