// Native components
import Head from 'next/head'

// Components
import Navbar from '@/components/navbar/Navbar';

// Hooks
import { useState, useEffect } from 'react'

export default function Home() {
  const [theme, setTheme] = useState("light");

  useEffect(() => {
    if (theme === "dark") {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  }, [theme])

  const handleThemeSwitch = () => {
    setTheme(theme === "dark" ? "light" : "dark");
  };

  return (
    <>
      <Head>
        <title>REST COUNTRIES</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen min-w-screen darkMode">
        <Navbar theme={theme} changeTheme={handleThemeSwitch}></Navbar>
      </main>
    </>
  )
}
